#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jupyter-nbgallery
Version  : 1.1.1
Release  : 36
URL      : https://files.pythonhosted.org/packages/87/03/9b2fd5d6073d265841427c0be05c137fb8b83a4e74cc1e9195cbf2046e20/jupyter-nbgallery-1.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/87/03/9b2fd5d6073d265841427c0be05c137fb8b83a4e74cc1e9195cbf2046e20/jupyter-nbgallery-1.1.1.tar.gz
Summary  : Jupyter extensions to add nbgallery integration
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: jupyter-nbgallery-bin = %{version}-%{release}
Requires: jupyter-nbgallery-license = %{version}-%{release}
Requires: jupyter-nbgallery-python = %{version}-%{release}
Requires: jupyter-nbgallery-python3 = %{version}-%{release}
Requires: notebook
BuildRequires : buildreq-distutils3
BuildRequires : notebook

%description
# Overview

%package bin
Summary: bin components for the jupyter-nbgallery package.
Group: Binaries
Requires: jupyter-nbgallery-license = %{version}-%{release}

%description bin
bin components for the jupyter-nbgallery package.


%package license
Summary: license components for the jupyter-nbgallery package.
Group: Default

%description license
license components for the jupyter-nbgallery package.


%package python
Summary: python components for the jupyter-nbgallery package.
Group: Default
Requires: jupyter-nbgallery-python3 = %{version}-%{release}

%description python
python components for the jupyter-nbgallery package.


%package python3
Summary: python3 components for the jupyter-nbgallery package.
Group: Default
Requires: python3-core
Provides: pypi(jupyter_nbgallery)
Requires: pypi(notebook)

%description python3
python3 components for the jupyter-nbgallery package.


%prep
%setup -q -n jupyter-nbgallery-1.1.1
cd %{_builddir}/jupyter-nbgallery-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599599156
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jupyter-nbgallery
cp %{_builddir}/jupyter-nbgallery-1.1.1/jupyter_nbgallery/nbextensions/instrumentation/crypto-js-license.txt %{buildroot}/usr/share/package-licenses/jupyter-nbgallery/1d0d2968b35836cde91ab65b1692d1546ffa4fb3
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter-nbgallery

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jupyter-nbgallery/1d0d2968b35836cde91ab65b1692d1546ffa4fb3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
