#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jupyter-nbgallery
Version  : 0.2.3
Release  : 1
URL      : https://pypi.python.org/packages/fc/c9/389b205878cfd269ed8277d6400bc689ac200315abaada39e5bd708fd21c/jupyter-nbgallery-0.2.3.tar.gz
Source0  : https://pypi.python.org/packages/fc/c9/389b205878cfd269ed8277d6400bc689ac200315abaada39e5bd708fd21c/jupyter-nbgallery-0.2.3.tar.gz
Summary  : Jupyter extensions to add nbgallery integration
Group    : Development/Tools
License  : MIT
Requires: jupyter-nbgallery-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
No detailed description available

%package python
Summary: python components for the jupyter-nbgallery package.
Group: Default

%description python
python components for the jupyter-nbgallery package.


%prep
%setup -q -n jupyter-nbgallery-0.2.3

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485738307
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1485738307
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
